# Generated by Django 3.1.7 on 2021-03-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='goods',
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ManyToManyField(related_name='good', to='goods.Category'),
        ),
    ]
